export const CONTEST_CATALOG = [
  {
    id: 'pc_al_2026',
    code: 'PC AL',
    name: 'Policia Civil de Alagoas',
    role: 'Agente e Escrivao',
    color: '#7c6af5',
    accent: '#38bdf8',
    icon: 'PC',
    priceCents: 14990,
    currency: 'BRL',
    contentStatus: 'ready',
    salesStatus: 'available',
    careerArea: 'police_security',
    careerSubarea: 'civil_police',
    subtopicCount: 137,
    questionCount: 6480,
    description: 'Jornada completa com edital verticalizado, questoes e batalhas.',
  },
  {
    id: 'pc_ba_2026',
    code: 'PC BA',
    name: 'PC BA 2026 — Investigador de Polícia Civil',
    role: 'Investigador de Polícia Civil',
    color: '#24104f',
    accent: '#37d6ff',
    icon: 'PCBA',
    priceCents: 6990,
    currency: 'BRL',
    contentStatus: 'ready',
    salesStatus: 'available',
    examDate: '2026-12-06',
    careerArea: 'police_security',
    careerSubarea: 'civil_police',
    subtopicCount: 296,
    questionCount: 1267,
    description: 'Jornada do Investigador com edital verticalizado, microconhecimentos e banco inicial de questões.',
  },
  {
    id: 'pm_ba_2026',
    code: 'PM BA',
    name: 'PM BA 2026 — Soldado',
    role: 'Aluno Soldado da Polícia Militar',
    color: '#102d25',
    accent: '#d6b34c',
    icon: 'PMBA',
    priceCents: 6999,
    currency: 'BRL',
    contentStatus: 'preparing',
    salesStatus: 'preorder',
    careerArea: 'police_security',
    careerSubarea: 'military_police',
    subtopicCount: 213,
    questionCount: 0,
    description: 'Pré-venda da jornada de Soldado da PM BA, com mapa pré-edital em preparação e acesso garantido após a publicação do conteúdo inicial.',
    coverAsset: 'assets/courses/pm-ba-2026.webp',
  },
  {
    id: 'pf_2026',
    code: 'PF',
    name: 'Policia Federal',
    role: 'Agente de Policia Federal',
    color: '#0f766e',
    accent: '#5eead4',
    icon: 'PF',
    priceCents: 18990,
    currency: 'BRL',
    contentStatus: 'preparing',
    salesStatus: 'coming_soon',
    careerArea: 'police_security',
    careerSubarea: 'federal_police',
    description: 'Modulo independente preparado para o proximo pacote editorial.',
  },
  {
    id: 'prf_2026',
    code: 'PRF',
    name: 'Policia Rodoviaria Federal',
    role: 'Policial Rodoviario Federal',
    color: '#b45309',
    accent: '#fbbf24',
    icon: 'PRF',
    priceCents: 17990,
    currency: 'BRL',
    contentStatus: 'preparing',
    salesStatus: 'coming_soon',
    careerArea: 'police_security',
    careerSubarea: 'federal_highway_police',
    description: 'Modulo independente pronto para receber edital e banco de questoes.',
  },
];

export function getContestById(contestId) {
  return CONTEST_CATALOG.find((contest) => contest.id === contestId) || null;
}

export function formatContestPrice(contest) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: contest.currency })
    .format(contest.priceCents / 100);
}
